version: '2.2'

services:
    mongo:
        image: mongo
        volumes:
            - ./data:/data/db
        restart: unless-stopped
    web:
        build:
            context: app 
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - "2727:80"
        external_links:
            - mongo


networks:
    default:
        enable_ipv6: true
        ipam:
            driver: default
            config:
                - subnet: "fdff:d0ce:2727::1/64"
